### ISSUE TITLE
Comparison between two GTX 1080 and one Pascal Titan X

### ISSUE THREAD

**Issue by mjohn123** [jcjohnson/cnn-benchmarks#10]
Thanks for your kind cnn-benchmarks. I have two options to setup my computer:
1. Buy 1 Pascal Titan X
2. Buy 2 Pascal GTX 1080 and bridge them

In my options, Which one is a better choice in term of speed and configuration?

**Comment by rishikksh20** [comment]
Go for single titan X because it has 12 gb memory whereas GTX 1080 only have 8 gb. Even though you bridge two GTX 1080 they still scale as  8gb memory not 16 gb because to syn GPU and CNN parameters both GPUs contain whole CNN model individually. And also there is no sophisticated implementation of CNN libraries which can utilise 100% performance from both GPUs while training.
Performance is heavily dependent on the PCIe topology of the system, the configuration of the neural network you are training, and the speed of each of the layers.  In general, scaling on 2 GPUs tends to be ~1.8X on average for networks like AlexNet, CaffeNet, VGG, GoogleNet.
